# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Assgmt4.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pbtn_CascadeView = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtn_CascadeView.sizePolicy().hasHeightForWidth())
        self.pbtn_CascadeView.setSizePolicy(sizePolicy)
        self.pbtn_CascadeView.setMinimumSize(QtCore.QSize(155, 65))
        self.pbtn_CascadeView.setObjectName("pbtn_CascadeView")
        self.horizontalLayout_5.addWidget(self.pbtn_CascadeView)
        self.pbtn_TileView = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtn_TileView.sizePolicy().hasHeightForWidth())
        self.pbtn_TileView.setSizePolicy(sizePolicy)
        self.pbtn_TileView.setMinimumSize(QtCore.QSize(155, 65))
        self.pbtn_TileView.setObjectName("pbtn_TileView")
        self.horizontalLayout_5.addWidget(self.pbtn_TileView)
        spacerItem = QtWidgets.QSpacerItem(428, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(478, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_nameField = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nameField.setObjectName("lbl_nameField")
        self.horizontalLayout.addWidget(self.lbl_nameField)
        self.lbl_Name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Name.setObjectName("lbl_Name")
        self.horizontalLayout.addWidget(self.lbl_Name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_StudentNumField = QtWidgets.QLabel(self.centralwidget)
        self.lbl_StudentNumField.setObjectName("lbl_StudentNumField")
        self.horizontalLayout_2.addWidget(self.lbl_StudentNumField)
        self.lbl_StudentNumber = QtWidgets.QLabel(self.centralwidget)
        self.lbl_StudentNumber.setObjectName("lbl_StudentNumber")
        self.horizontalLayout_2.addWidget(self.lbl_StudentNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_UrlField = QtWidgets.QLabel(self.centralwidget)
        self.lbl_UrlField.setObjectName("lbl_UrlField")
        self.horizontalLayout_3.addWidget(self.lbl_UrlField)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.mdiArea.setDocumentMode(True)
        self.mdiArea.setTabsClosable(True)
        self.mdiArea.setTabsMovable(True)
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow = QtWidgets.QWidget()
        self.subwindow.setObjectName("subwindow")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.subwindow)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.subW_descript_lbl = QtWidgets.QLabel(self.subwindow)
        self.subW_descript_lbl.setObjectName("subW_descript_lbl")
        self.verticalLayout_4.addWidget(self.subW_descript_lbl)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.subW_fName_lbl = QtWidgets.QLabel(self.subwindow)
        self.subW_fName_lbl.setObjectName("subW_fName_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.subW_fName_lbl)
        self.subW_dob_lbl = QtWidgets.QLabel(self.subwindow)
        self.subW_dob_lbl.setObjectName("subW_dob_lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.subW_dob_lbl)
        self.subW_projectId_lbl = QtWidgets.QLabel(self.subwindow)
        self.subW_projectId_lbl.setObjectName("subW_projectId_lbl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.subW_projectId_lbl)
        self.subW_projRoleId_lbl = QtWidgets.QLabel(self.subwindow)
        self.subW_projRoleId_lbl.setObjectName("subW_projRoleId_lbl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.subW_projRoleId_lbl)
        self.subW_phone_lbl = QtWidgets.QLabel(self.subwindow)
        self.subW_phone_lbl.setObjectName("subW_phone_lbl")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.subW_phone_lbl)
        self.subW_email_lbl = QtWidgets.QLabel(self.subwindow)
        self.subW_email_lbl.setObjectName("subW_email_lbl")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.subW_email_lbl)
        self.subW_fname_ledit = QtWidgets.QLineEdit(self.subwindow)
        self.subW_fname_ledit.setObjectName("subW_fname_ledit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.subW_fname_ledit)
        self.subW_dob_ledit = QtWidgets.QLineEdit(self.subwindow)
        self.subW_dob_ledit.setObjectName("subW_dob_ledit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.subW_dob_ledit)
        self.subW_projId_ledit = QtWidgets.QLineEdit(self.subwindow)
        self.subW_projId_ledit.setObjectName("subW_projId_ledit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.subW_projId_ledit)
        self.subW_projRoleId_ledit = QtWidgets.QLineEdit(self.subwindow)
        self.subW_projRoleId_ledit.setObjectName("subW_projRoleId_ledit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.subW_projRoleId_ledit)
        self.subW_phone_ledit = QtWidgets.QLineEdit(self.subwindow)
        self.subW_phone_ledit.setObjectName("subW_phone_ledit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.subW_phone_ledit)
        self.subW_email_ledit = QtWidgets.QLineEdit(self.subwindow)
        self.subW_email_ledit.setObjectName("subW_email_ledit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.subW_email_ledit)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.subW_submit_btn = QtWidgets.QPushButton(self.subwindow)
        self.subW_submit_btn.setObjectName("subW_submit_btn")
        self.verticalLayout_4.addWidget(self.subW_submit_btn)
        self.subW_confirm_lbl = QtWidgets.QLabel(self.subwindow)
        self.subW_confirm_lbl.setObjectName("subW_confirm_lbl")
        self.verticalLayout_4.addWidget(self.subW_confirm_lbl)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.label_17 = QtWidgets.QLabel(self.subwindow)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("Downloads/iset.jpg"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.subwindow_2 = QtWidgets.QWidget()
        self.subwindow_2.setObjectName("subwindow_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.subwindow_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.subW2_descript_lbl = QtWidgets.QLabel(self.subwindow_2)
        self.subW2_descript_lbl.setObjectName("subW2_descript_lbl")
        self.verticalLayout_3.addWidget(self.subW2_descript_lbl)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.subW2_userName_lbl = QtWidgets.QLabel(self.subwindow_2)
        self.subW2_userName_lbl.setObjectName("subW2_userName_lbl")
        self.horizontalLayout_6.addWidget(self.subW2_userName_lbl)
        self.subW2_userName_ledit = QtWidgets.QLineEdit(self.subwindow_2)
        self.subW2_userName_ledit.setObjectName("subW2_userName_ledit")
        self.horizontalLayout_6.addWidget(self.subW2_userName_ledit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.subW2_password_lbl = QtWidgets.QLabel(self.subwindow_2)
        self.subW2_password_lbl.setObjectName("subW2_password_lbl")
        self.horizontalLayout_7.addWidget(self.subW2_password_lbl)
        self.subW2_password_ledit = QtWidgets.QLineEdit(self.subwindow_2)
        self.subW2_password_ledit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.subW2_password_ledit.setObjectName("subW2_password_ledit")
        self.horizontalLayout_7.addWidget(self.subW2_password_ledit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.subW2_login_btn = QtWidgets.QPushButton(self.subwindow_2)
        self.subW2_login_btn.setObjectName("subW2_login_btn")
        self.verticalLayout_3.addWidget(self.subW2_login_btn)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.welcomescreen_lbl = QtWidgets.QLabel(self.subwindow_2)
        self.welcomescreen_lbl.setText("")
        self.welcomescreen_lbl.setPixmap(QtGui.QPixmap("Downloads/iset.jpg"))
        self.welcomescreen_lbl.setObjectName("welcomescreen_lbl")
        self.gridLayout_2.addWidget(self.welcomescreen_lbl, 0, 1, 1, 1)
        self.subW2_loginMessage_lbl = QtWidgets.QLabel(self.subwindow_2)
        self.subW2_loginMessage_lbl.setObjectName("subW2_loginMessage_lbl")
        self.gridLayout_2.addWidget(self.subW2_loginMessage_lbl, 1, 0, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_2)
        self.subwindow_3 = QtWidgets.QWidget()
        self.subwindow_3.setObjectName("subwindow_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.subwindow_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.subW3_descript_lbl = QtWidgets.QLabel(self.subwindow_3)
        self.subW3_descript_lbl.setObjectName("subW3_descript_lbl")
        self.verticalLayout_5.addWidget(self.subW3_descript_lbl)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtWidgets.QLabel(self.subwindow_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_12 = QtWidgets.QLabel(self.subwindow_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.subwindow_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.subW3_memberId_ledit = QtWidgets.QLineEdit(self.subwindow_3)
        self.subW3_memberId_ledit.setObjectName("subW3_memberId_ledit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.subW3_memberId_ledit)
        self.subW3_name_ledit = QtWidgets.QLineEdit(self.subwindow_3)
        self.subW3_name_ledit.setObjectName("subW3_name_ledit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.subW3_name_ledit)
        self.subW3_dob_ledit = QtWidgets.QLineEdit(self.subwindow_3)
        self.subW3_dob_ledit.setObjectName("subW3_dob_ledit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.subW3_dob_ledit)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.subW3_submit_btn = QtWidgets.QPushButton(self.subwindow_3)
        self.subW3_submit_btn.setObjectName("subW3_submit_btn")
        self.verticalLayout_5.addWidget(self.subW3_submit_btn)
        self.subW3_confirm_lbl = QtWidgets.QLabel(self.subwindow_3)
        self.subW3_confirm_lbl.setObjectName("subW3_confirm_lbl")
        self.verticalLayout_5.addWidget(self.subW3_confirm_lbl)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.label_16 = QtWidgets.QLabel(self.subwindow_3)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("Downloads/iset.jpg"))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 22))
        self.menubar.setObjectName("menubar")
        self.menuSubWindow_View = QtWidgets.QMenu(self.menubar)
        self.menuSubWindow_View.setObjectName("menuSubWindow_View")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuData_Maintainence = QtWidgets.QMenu(self.menubar)
        self.menuData_Maintainence.setObjectName("menuData_Maintainence")
        self.menuReporting = QtWidgets.QMenu(self.menubar)
        self.menuReporting.setObjectName("menuReporting")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCascade_View = QtWidgets.QAction(MainWindow)
        self.actionCascade_View.setObjectName("actionCascade_View")
        self.actionTile_View = QtWidgets.QAction(MainWindow)
        self.actionTile_View.setObjectName("actionTile_View")
        self.actionNew_File = QtWidgets.QAction(MainWindow)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionAdd_New_Record = QtWidgets.QAction(MainWindow)
        self.actionAdd_New_Record.setObjectName("actionAdd_New_Record")
        self.actionDelete_existing_record = QtWidgets.QAction(MainWindow)
        self.actionDelete_existing_record.setObjectName("actionDelete_existing_record")
        self.menuSubWindow_View.addAction(self.actionCascade_View)
        self.menuSubWindow_View.addAction(self.actionTile_View)
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuData_Maintainence.addAction(self.actionAdd_New_Record)
        self.menuData_Maintainence.addAction(self.actionDelete_existing_record)
        self.menubar.addAction(self.menuSubWindow_View.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuData_Maintainence.menuAction())
        self.menubar.addAction(self.menuReporting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.pbtn_CascadeView.clicked.connect(self.mdiArea.cascadeSubWindows)
        self.pbtn_TileView.clicked.connect(self.mdiArea.tileSubWindows)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbtn_CascadeView.setText(_translate("MainWindow", "Cascade View"))
        self.pbtn_TileView.setText(_translate("MainWindow", "Tile View"))
        self.lbl_nameField.setText(_translate("MainWindow", "Name:"))
        self.lbl_Name.setText(_translate("MainWindow", "Mandla Ndlovu"))
        self.lbl_StudentNumField.setText(_translate("MainWindow", "Student Number:"))
        self.lbl_StudentNumber.setText(_translate("MainWindow", "32349866"))
        self.lbl_UrlField.setText(_translate("MainWindow", "CE Project URL:"))
        self.label.setText(_translate("MainWindow", "https:/www.unisa.ac.za/sites/cor"))
        self.subwindow.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.subW_descript_lbl.setText(_translate("MainWindow", "Add new member record"))
        self.subW_fName_lbl.setText(_translate("MainWindow", "Full Name"))
        self.subW_dob_lbl.setText(_translate("MainWindow", "Date of birth"))
        self.subW_projectId_lbl.setText(_translate("MainWindow", "Project ID:"))
        self.subW_projRoleId_lbl.setText(_translate("MainWindow", "Project role ID:"))
        self.subW_phone_lbl.setText(_translate("MainWindow", "Phone number:"))
        self.subW_email_lbl.setText(_translate("MainWindow", "Email address:"))
        self.subW_submit_btn.setText(_translate("MainWindow", "Submit"))
        self.subW_confirm_lbl.setText(_translate("MainWindow", "Confirmation message"))
        self.subwindow_2.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.subW2_descript_lbl.setText(_translate("MainWindow", "Enter your user login details below"))
        self.subW2_userName_lbl.setText(_translate("MainWindow", "User Name:"))
        self.subW2_password_lbl.setText(_translate("MainWindow", "Password:"))
        self.subW2_login_btn.setText(_translate("MainWindow", "Login"))
        self.subW2_loginMessage_lbl.setText(_translate("MainWindow", "Login confirmation"))
        self.subwindow_3.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.subW3_descript_lbl.setText(_translate("MainWindow", "Delete existing member"))
        self.label_14.setText(_translate("MainWindow", "Member ID:"))
        self.label_12.setText(_translate("MainWindow", "Full Name:"))
        self.label_13.setText(_translate("MainWindow", "Date of birth:"))
        self.subW3_submit_btn.setText(_translate("MainWindow", "Submit"))
        self.subW3_confirm_lbl.setText(_translate("MainWindow", "Confirmation message"))
        self.menuSubWindow_View.setTitle(_translate("MainWindow", "SubWindow View"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuData_Maintainence.setTitle(_translate("MainWindow", "Data Maintainence"))
        self.menuReporting.setTitle(_translate("MainWindow", "Reporting"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionCascade_View.setText(_translate("MainWindow", "Cascade View"))
        self.actionTile_View.setText(_translate("MainWindow", "Tile View"))
        self.actionNew_File.setText(_translate("MainWindow", "New File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionAdd_New_Record.setText(_translate("MainWindow", "Add New Record"))
        self.actionDelete_existing_record.setText(_translate("MainWindow", "Delete existing record"))

